config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant
    validates :content, :rating, presence: true
    validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
      end

      def show
        @restaurant = Restaurant.find(params[:id])
        @review = Review.new
      end

      def new
        @restaurant = Restaurant.new
      end

      def create
        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            redirect_to restaurant_path(@restaurant)
          else
            render :new
          end
      end

      private

      def restaurant_params
        params.require(:restaurant).permit(:name, :address, :phone_number, :category)
      end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_restaurant, only: [:index, :new, :create]

  def index
    @reviews = Review.where(restaurant_id: @restaurant)
  end

  def new
    # we need @restaurant in `simple_form_for`
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <img src="https://images.unsplash.com/photo-1556742205-e10c9486e506?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="Table with bowl" class="avatar">
      <span class="navbar-brand">Restaurants MVP</span>
      <span class="navbar-brand"><%= link_to "Home", restaurants_path %></span>
      <span class="navbar-brand"><%= link_to "Add", new_restaurant_path %> </span>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, placeholder: "Write the restaurant name here" %>
  <%= f.input :address, placeholder: "Write the restaurant name here" %>
  <%= f.input :category, placeholder: "Write the category here (out of 'chinese', 'italian', japanese, 'french' and 'belgian')" %>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants:</h1>

<div class="container">
<ol>
<% @restaurants.each do |r| %>
  <li class="card"><%= link_to r.name, restaurant_path(r), class: "link" %></li>
<% end %>
</ol>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.submit "Add a Restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2>Address: <%=  @restaurant.address%></h2>
<h3>Category: <%= @restaurant.category %></h3>

<%= link_to 'Reviews', restaurant_reviews_path(@restaurant) %>

<br>
<br>

<%= render 'reviews/form' %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, placeholder: "Write your review here" %>
  <%= f.input :rating, placeholder: "Add a rating (1-5)" %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews:</h1>

<ol>
<% @reviews.each do |r| %>
  <li class="card"><%= r.content %> (Rating: <%= r.rating %>)</li>
<% end %>
</ol>


<%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>Add your review below:</h1>
<%= render 'form', restaurant: @restaurant, review: @review %>

<br>
<%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %>